import { test, expect } from "@playwright/test";
import { mkdtemp, mkdir, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import path from "node:path";

test("rules-first policies support templates, multiple connections, tests, apply and restore", async ({ page, request }) => {
  page.setDefaultTimeout(10000);
  const root = await mkdtemp(path.join(tmpdir(), "relay-policy-browser-"));
  const sessions = path.join(root, "sessions"), project = path.join(root, "project");
  await mkdir(sessions); await mkdir(project); await writeFile(path.join(project, "README.md"), "Synthetic documentation");
  const response = await request.post("/api/connections", { data: { name: "Policy browser fixture", provider: "codex_cli", path: sessions } });
  expect(response.ok()).toBeTruthy(); const connection = await response.json();
  const secondary = path.join(root, "secondary"); await mkdir(secondary);
  const second = await (await request.post("/api/connections", { data: { name: "Policy second fixture", provider: "codex_cli", path: secondary } })).json();
  try {
    await page.goto("/#safety"); await page.getByRole("button", { name: "Policies", exact: true }).click();
    await expect(page.getByText("Protection is configured per connection")).toHaveCount(0);
    await expect(page.getByRole("button", { name: "Add connection", exact: true })).toHaveCount(0);
    await page.screenshot({ path: "../data/qa/policies-start-desktop.png", fullPage: true });
    await page.getByRole("button", { name: "Add rule", exact: true }).click();
    await page.getByLabel("Presets").getByRole("button", { name: "Review Git pushes", exact: true }).click();
    await expect(page.getByRole("combobox", { name: "When", exact: true })).toHaveValue("git_push");
    await page.getByRole("combobox", { name: "Connections", exact: true }).selectOption("selected");
    await page.getByRole("checkbox", { name: "Policy browser fixture", exact: true }).check();
    await page.getByRole("checkbox", { name: "Policy second fixture", exact: true }).check();
    await page.screenshot({ path: "../data/qa/policies-editor-desktop.png", fullPage: true });
    await page.getByRole("button", { name: "Save rule", exact: true }).click();
    await expect(page.getByRole("button", { name: "Review changes", exact: true })).toBeVisible();
    let state = await (await request.get("/api/safety/policies")).json();
    const firstDraft = state.draft_id;
    expect(state.versions.find((v: any) => v.id === firstDraft).rules[0].connection_ids).toHaveLength(2);
    await page.getByRole("button", { name: "Edit Review Git pushes", exact: true }).click();
    await page.getByRole("textbox", { name: "Rule name", exact: true }).fill("Review pushes");
    await page.getByRole("button", { name: "Save rule", exact: true }).click();
    await expect(page.getByText("Review pushes", { exact: true }).first()).toBeVisible();
    state = await (await request.get("/api/safety/policies")).json();
    expect(state.draft_id).toBe(firstDraft); expect(state.versions).toHaveLength(1);
    await page.getByRole("button", { name: "Remove Review pushes", exact: true }).click();
    await expect(page.getByRole("dialog", { name: "Remove rule?" })).toBeVisible();
    await page.getByRole("dialog").getByRole("button", { name: "Cancel", exact: true }).click();
    await expect(page.getByText("Review pushes", { exact: true }).first()).toBeVisible();
    await page.reload(); await page.getByRole("button", { name: "Policies", exact: true }).click();
    await expect(page.getByText("Review pushes", { exact: true }).first()).toBeVisible();
    await expect(page.getByRole("button", { name: "Apply changes", exact: true })).toBeEnabled();
    await page.getByRole("button", { name: "Apply changes", exact: true }).click();
    await expect(page.getByRole("dialog", { name: "Apply without simulating?" })).toBeVisible();
    await page.getByRole("button", { name: "Cancel", exact: true }).click();
    let finishToggle!: () => void;
    const toggleSave = new Promise<void>(resolve => { finishToggle = resolve; });
    await page.route("**/api/safety/policies/draft", async route => { await toggleSave; await route.continue(); }, { times: 1 });
    await page.getByRole("switch", { name: "Enable Review pushes", exact: true }).click();
    await expect(page.getByRole("button", { name: "Add rule", exact: true })).toBeDisabled();
    await expect(page.getByRole("button", { name: "Add rule", exact: true })).toHaveCSS("opacity", "1");
    await expect(page.getByRole("button", { name: "Apply changes", exact: true })).toHaveCSS("opacity", "1");
    finishToggle();
    await expect(page.getByRole("switch", { name: "Enable Review pushes", exact: true })).not.toBeChecked();
    await page.getByRole("switch", { name: "Enable Review pushes", exact: true }).click();
    await page.getByRole("button", { name: "Simulate past requests", exact: true }).click();
    await expect(page.getByText("No past requests to test", { exact: true })).toBeVisible();
    await page.getByRole("button", { name: "Live requests", exact: true }).click();
    await page.getByRole("button", { name: "Start live simulation", exact: true }).click();
    await expect(page.getByRole("button", { name: "Stop live simulation", exact: true })).toBeVisible();
    expect((await (await request.get("/api/safety/policies")).json()).active_id).toBeNull();
    await page.getByRole("button", { name: "Apply changes", exact: true }).click();
    await expect(page.getByRole("button", { name: "Pause rules", exact: true })).toBeVisible();
    const first = (await (await request.get("/api/safety/policies")).json()).active_id;
    await page.getByRole("button", { name: "Add rule", exact: true }).click();
    await page.getByLabel("Presets").getByRole("button", { name: "Block sensitive-file access", exact: true }).click();
    await page.setViewportSize({ width: 390, height: 844 });
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBeTruthy();
    await page.screenshot({ path: "../data/qa/policies-editor-mobile.png", fullPage: true });
    await page.getByRole("button", { name: "Save rule", exact: true }).click();
    await expect(page.getByText("Review pushes", { exact: true }).first()).toBeVisible();
    await expect(page.getByText("Block sensitive-file access", { exact: true }).first()).toBeVisible();
    await page.getByRole("button", { name: "Review changes", exact: true }).click();
    await page.screenshot({ path: "../data/qa/policies-draft-mobile.png", fullPage: true });
    await page.getByRole("dialog").getByRole("button", { name: "Close", exact: true }).click();
    await page.getByRole("button", { name: "Simulate past requests", exact: true }).click();
    await page.getByRole("button", { name: "Apply changes", exact: true }).click();
    await expect(page.getByRole("button", { name: "Pause rules", exact: true })).toBeVisible();
    await page.setViewportSize({ width: 1440, height: 1000 });
    await page.getByRole("button", { name: "History", exact: true }).click();
    await expect(page.getByLabel("Policy history").locator("details")).toHaveCount(2);
    await page.getByLabel("Policy history").locator("details").last().locator("summary").click();
    await page.screenshot({ path: "../data/qa/policies-history-desktop.png", fullPage: true });
    await page.getByRole("button", { name: "Restore as draft", exact: true }).click();
    state = await (await request.get("/api/safety/policies")).json();
    expect(state.active_id).not.toBe(first);
    await expect(page.getByText("Removed", { exact: true })).toBeVisible();
    await page.screenshot({ path: "../data/qa/policies-draft-desktop.png", fullPage: true });
    await page.getByRole("dialog").getByRole("button", { name: "Close", exact: true }).click();
    await page.getByRole("button", { name: "Discard draft", exact: true }).click();
    await page.getByRole("button", { name: "Discard changes", exact: true }).click();
    await expect(page.getByRole("button", { name: "Pause rules", exact: true })).toBeVisible();
    await page.getByRole("button", { name: "Pause rules", exact: true }).click();
    await expect(page.getByRole("button", { name: "Resume rules", exact: true })).toBeVisible();
    await expect(page.getByText("Review pushes", { exact: true }).first()).toBeVisible();
    await page.reload(); await page.getByRole("button", { name: "Policies", exact: true }).click();
    await expect(page.getByRole("button", { name: "Discard draft", exact: true })).toHaveCount(0);
    await expect(page.getByRole("button", { name: "Resume rules", exact: true })).toBeVisible();
    await page.screenshot({ path: "../data/qa/policies-paused.png", fullPage: true });
    await page.getByRole("button", { name: "Resume rules", exact: true }).click();
    await expect(page.getByRole("button", { name: "Pause rules", exact: true })).toBeVisible();
    await page.getByRole("switch", { name: "Enable Review pushes", exact: true }).click();
    await page.getByRole("button", { name: "Apply changes", exact: true }).click();
    await page.getByRole("checkbox", { name: "Don’t ask again in this browser" }).check();
    await page.screenshot({ path: "../data/qa/policies-untested-warning.png", fullPage: true });
    await page.getByRole("button", { name: "Apply anyway" }).click();
    await expect(page.getByRole("switch", { name: "Enable Review pushes", exact: true })).not.toBeChecked();
    await page.getByRole("button", { name: "Back to Safety" }).click();
    await page.getByRole("button", { name: "Settings", exact: true }).click();
    await expect(page.getByRole("switch", { name: "Warn before applying an unsimulated draft" })).not.toBeChecked();
    await page.getByRole("switch", { name: "Warn before applying an unsimulated draft" }).check();
    await page.getByRole("button", { name: "Close safety settings" }).click();
    await page.getByRole("button", { name: "Policies", exact: true }).click();
    await page.getByRole("switch", { name: "Enable Review pushes", exact: true }).click();
    await page.getByRole("button", { name: "Apply changes", exact: true }).click();
    await expect(page.getByRole("dialog", { name: "Apply without simulating?" })).toBeVisible();
    await page.getByRole("button", { name: "Cancel", exact: true }).click();
    await page.setViewportSize({ width: 390, height: 844 });
    await page.screenshot({ path: "../data/qa/policies-simulation-mobile.png", fullPage: true });
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBeTruthy();
    await page.evaluate(() => window.scrollTo(0, document.documentElement.scrollHeight));
    const runBox = await page.getByRole("button", { name: "Simulate past requests", exact: true }).boundingBox();
    const navBox = await page.locator(".sidebar").boundingBox();
    expect(runBox!.y + runBox!.height).toBeLessThan(navBox!.y);
    await page.screenshot({ path: "../data/qa/policies-simulation-toolbar-mobile.png" });
  } finally {
    try {
      for (const action of ["disable", "stop_trial"]) {
        const state = await (await request.get("/api/safety/policies")).json();
        await request.post("/api/safety/policies/transition", { data: { revision: state.revision, action } });
      }
      await request.delete(`/api/connections/${connection.id}`);
      await request.delete(`/api/connections/${second.id}`);
    } catch { /* Isolated server teardown clears fixtures. */ }
  }
});
