import { test, expect } from "@playwright/test";

test("starter rules save as a draft and presets replace their conditions", async ({ page }) => {
  let state: any = { revision: 0, draft_id: null, active_id: null, paused_id: null, trial_id: null, versions: [], changes: [] };
  const writes: any[] = [];
  await page.route("**/api/safety/policies", route => route.fulfill({ json: state }));
  await page.route("**/api/safety/policies/draft", async route => {
    const body = route.request().postDataJSON();
    writes.push(body);
    state = { ...state, revision: state.revision + 1, draft_id: 1, versions: [{ id: 1, name: body.name, rules: body.rules, created_at: new Date().toISOString(), previewed_at: null, trial_started_at: null, ever_active: false, conflicts: [] }] };
    await route.fulfill({ json: { revision: state.revision } });
  });
  await page.goto("/#safety");
  await page.getByRole("button", { name: "Policies", exact: true }).click();
  await expect(page.getByText("A few rules go a long way")).toBeVisible();
  await page.screenshot({ path: "../data/qa/policy-starter-desktop.png", fullPage: true });
  await page.setViewportSize({ width: 390, height: 844 });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBeTruthy();
  await page.screenshot({ path: "../data/qa/policy-starter-mobile.png", fullPage: true });
  await page.getByRole("button", { name: "Add suggested rules", exact: true }).click();
  await expect(page.getByRole("button", { name: "Apply changes", exact: true })).toBeVisible();
  expect(writes[0].rules).toHaveLength(4);
  expect(new Set(writes[0].rules.map((r: any) => r.id)).size).toBe(4);
  expect(writes[0].rules.every((r: any) => r.filenames.length || r.command_contains)).toBeTruthy();
  expect(writes[0].rules[0]).toMatchObject({ activity: "read", effect: "deny", filenames: [".env", ".env.*", "*.pem", "id_rsa", "id_ed25519"] });
  expect(state.active_id).toBeNull();
  await page.getByRole("button", { name: "Live", exact: true }).click();
  await expect(page.getByRole("button", { name: "Add suggested rules", exact: true })).toHaveCount(0);
  await page.getByRole("button", { name: "Draft 4 changes", exact: true }).click();
  await page.getByRole("button", { name: "Add rule", exact: true }).click();
  const presets = page.getByRole("complementary", { name: "Presets" });
  await expect(presets.getByRole("button")).toHaveCount(6);
  await presets.getByRole("button", { name: /Ask before changing dependencies/ }).click();
  await expect(page.getByLabel("File names (optional)")).toHaveValue(/package.json/);
  await presets.getByRole("button", { name: /Review force pushes/ }).click();
  await expect(page.getByLabel("Command contains (optional)")).toBeVisible();
  await expect(page.getByLabel("Command contains (optional)")).toHaveValue("--force");
  await presets.getByRole("button", { name: /Review Git cleanup/ }).click();
  await expect(page.getByLabel("Command contains (optional)")).toHaveValue("git clean");
  await presets.getByRole("button", { name: /Review new pull requests/ }).click();
  await expect(page.getByLabel("Exact tool name", { exact: true })).toHaveValue("mcp__github__create_pull_request");
  await presets.getByRole("button", { name: /Ask before publishing to npm/ }).click();
  await expect(page.getByLabel("Command contains (optional)")).toHaveValue("npm publish");
  await page.screenshot({ path: "../data/qa/policy-presets-mobile.png", fullPage: true });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBeTruthy();
  await page.setViewportSize({ width: 1440, height: 1000 });
  await page.screenshot({ path: "../data/qa/policy-presets-desktop.png", fullPage: true });
  await page.getByRole("button", { name: "Save rule", exact: true }).click();
  await expect(page.getByRole("button", { name: "Add rule", exact: true })).toBeVisible();
  expect(writes[1].rules[4]).toMatchObject({ activity: "shell", command_contains: "npm publish", tool_name: "", filenames: [], effect: "review" });
});
