import { test, expect } from "@playwright/test";

test("Claude Code setup, search, chart and Explorer", async ({ page, request }) => {
  await page.goto("/");
  await page.getByRole("button", { name: /^Connections/ }).click();
  await page.getByRole("button", { name: "Add connection", exact: true }).first().click();
  const dialog = page.getByRole("dialog");
  await dialog.getByRole("radio", { name: "Claude Code", exact: true }).check();
  await expect(dialog.getByRole("status")).toContainText("1 conversation found");
  await dialog.getByText("Another profile or folder", { exact: true }).click();
  await expect(dialog.getByLabel("Archived conversations (separate connection)")).toHaveCount(0);
  await expect(dialog.getByLabel("Sessions directory")).toHaveValue(/e2e-claude-profile.*projects/);
  await expect(dialog.getByLabel("Detected source")).not.toContainText("e2e-mixed");
  await dialog.getByRole("button", { name: "Check source", exact: true }).click();
  await expect(dialog).toContainText("1 Claude Code sessions");
  await page.screenshot({ path: "../data/qa/claude-setup.png" });
  await dialog.getByRole("button", { name: "Connect", exact: true }).click();
  const card = page.locator(".connection-card").filter({ hasText: "Claude Code · Local transcript watcher" });
  await card.getByRole("button", { name: "Sync now" }).click();
  await expect(card).toContainText("1 sessions imported");
  await card.getByRole("button", { name: "Check source", exact: true }).click();
  await expect(card).toContainText("1 Claude Code sessions");
  const connections = await (await request.get("/api/connections")).json();
  const claude = connections.find((c: {provider: string}) => c.provider === "claude_code");
  await page.getByRole("button", { name: "Overview", exact: true }).click();
  await page.getByLabel("Filter connection").selectOption(claude.id);
  await page.getByLabel("Color bars by").selectOption("conversation");
  await expect(page.getByLabel("Conversation colors")).toHaveCount(0);
  await page.getByRole("button", { name: /Review Claude adapter/ }).first().click();
  await page.locator("details").filter({ hasText: "Claude fixture file contents" }).locator("summary").click();
  await expect(page.getByText("Claude fixture file contents", { exact: true })).toBeVisible();
  await page.screenshot({ path: "../data/qa/claude-explorer.png" });
  await page.getByRole("button", { name: "Overview", exact: true }).click();
  await page.setViewportSize({ width: 390, height: 844 });
  await page.getByRole("button", { name: /^Connections/ }).click();
  await page.getByRole("button", { name: "Add connection", exact: true }).first().click();
  await dialog.getByRole("radio", { name: "Claude Code", exact: true }).check();
  await expect(dialog.getByRole("button", { name: "Already connected", exact: true })).toBeDisabled();
  expect(await dialog.evaluate(el => el.scrollWidth <= el.clientWidth)).toBeTruthy();
  await page.screenshot({ path: "../data/qa/claude-setup-mobile.png" });
});
